 # Site menu settings
calina-docs:
  - title: "Getting Started"
    url: "#getting-started"
  - title: "How to Install Ghost 2"
    url: "#how-to-install-ghost"
  - title: "How to Install Theme2"
    url: "#how-to-install-theme"
  - title: "Static Pages"
    url: "#static-pages"
  - title: "Navigation"
    url: "#navigation"
  - title: "Disqus Comments"
    url: "#disqus-comment"
  - title: "Instagram"
    url: "#instagram"
  - title: "Posts Per Page"
    url: "#posts-per-page"
  - title: "Related Posts"
    url: "#related-posts"
  - title: "Subscribe Form"
    url: "#subscribe-form"
  - title: "Social Media Links"
    url: "#social-media-links"
  - title: "Update Favicon"
    url: "#update-favicon"
  - title: "Theme Development"
    url: "#theme-development"
# End
