# Welcome to Frasco!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Fluxtheme: Premium WordPress & Ghost Theme"
email: fluxtheme@gmail.com
description: Quick starter project for Jekyll including full setup for gulp, Sass, Autoprefixer, Bourbon/Neat/Bitters, Browserify, imagemin, Browsersync, PostCSS etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fluxtheme
github_username:  fluxtheme

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md

  # Site menu settings
menu:
  - title: "Getting Started"
    url: "#getting-started"
  - title: "How to Install Ghost"
    url: "#how-to-install-ghost"
  - title: "How to Install Theme"
    url: "#how-to-install-theme"
  - title: "Static Pages"
    url: "#static-pages"
  - title: "Navigation"
    url: "#navigation"
  - title: "Disqus Comments"
    url: "#disqus-comment"
  - title: "Instagram"
    url: "#instagram"
  - title: "Posts Per Page"
    url: "#posts-per-page"
  - title: "Related Posts"
    url: "#related-posts"
  - title: "Subscribe Form"
    url: "#subscribe-form"
  - title: "Social Media Links"
    url: "#social-media-links"
  - title: "Update Favicon"
    url: "#update-favicon"
  - title: "Theme Development"
    url: "#theme-development"
# End
